# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "S.M.Azwad-Ul-Alam"
author: "S.M.Azwad-Ul-Alam"
email: "azwadfahim@gmail.com.com"
#google_analytics: ""

logo_style: |
  max-width: 200px;
  border-radius: 50%;
  margin: 20px auto;
  display: block;

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/fahimazwad/
  GitHub: https://github.com/Fahim-Azwad